### ISSUE TITLE
Remaining Time header doesn't fit into the panel

### ISSUE THREAD

**Issue by raymoo69** [Zharay/KanColleViewer#15]
![unti5tled](https://f.cloud.github.com/assets/6552325/2070725/577693b2-8d1f-11e3-90f0-83f338001d13.png)
See pic. seems to be present in all menus where docks are used.

**Comment by thethingexe** [comment]
Should it just be change to "Completion" and "Remaining"

**Comment by Zharay** [comment]
Changed them over like I did with the horizontal version.
