### ISSUE TITLE
Mistranslate

### ISSUE THREAD

**Issue by silfumus** [Zharay/KanColleViewer#22]
commit 3d43a2c10b7810bbb5a6463bf543270fcabfef85

at _resources/translations/Quests.xml_, line 694,
it should be _Scrap your equipment 24 times_.

just noticed it while doing the quest, the progress indicator didn't appear at all even though i already scrapped more than 30 equipment.

**Comment by Zharay** [comment]
Alright fixed that and all the other scrap equipment lines so that they are consistent. Thanks for that heads up!
