### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by cleeezzz** [Zharay/KanColleViewer#28]
When I updated to the version right before .350, I started having issues with the translation.  KCV didn't detect the translation files and would default to japanese names for ships/equips/etc.  I changed the language setting to (auto) as well as English.  UI is in english in both but translations were still not used.  After deleting the appended translation folder and restarting about ~3 times, then it would detect translation files.  Not sure what the problem is.  I'm on Win7, running with admin priv.

**Comment by Zharay** [comment]
Are you using Japanese locale on your system?

**Comment by cleeezzz** [comment]
Nope, it just doesn't detect the translation files.  Under "Check for updates", everything except the App version is blank.  After restarting KCV a few times, then it'll just magically work.

**Comment by erwinumali** [comment]
Hello, I'm also having a similar issue. It only detects translation on the first run of the app, and reverts to Japanese on subsequent runs. I've resorted to re-extracting from the .rar every time I run it so that it would always translate properly.

Running on Win8 64 bit with admin privileges on KCV. Using the Horizontal one. I'm on English locale.

**Comment by kimura92** [comment]
I had the same problem here...
And I did a diagnos for this problem
What I did: Run directly from KCV folder / Run from shortcut created in Metro(Automatically created) / Run from shortcut pinned to Start/Taskbar / Run from shortcut on desktop
This is the result:
1/ Run directly from KCV / Run from shortcut on desktop : Check in Updates tab / Every file is up-to-date(shows version) - translated texts
2/ Run from shortcut in Start/Metro or on Taskbar : Check in Updates tab/No version is shown(I think this is the bug) - texts will NOT be translated.

---

So I recommend who gets this problem: please run DIRECTLY or create shortcut on desktop,DO NOT run from taskbat/start or metro.

**Comment by erwinumali** [comment]
@kimura92, that seems to have mitigated the problem for me. Thank you!

**Comment by Zharay** [comment]
I totally forgot that KCV even makes a metro app link. Most likely whats going on is that it now thinks that wherever metro stores the application's data is where that exe/link is located it. If you did a system search for something like "Equipment.xml" you'll most likely find a fully japanese populated file wherever it may be at.

I'll look into that, but this does actually show a bug with my auto generated translations, forgot to put in the version number with each file, thus its probably breaking at some point.
