### ISSUE TITLE
Compile source and use in Linux environment

### ISSUE THREAD

**Issue by kimura92** [Zharay/KanColleViewer#29]
I have a question
I mainly use Ubuntu on my computer
Can I compile and build a version for running on Ubuntu from the source?

**Comment by Zharay** [comment]
Don't think you can without redoing a lot of the things the core aspect of rendering the game through a browser (which is just Internet Explorer) and the code and elements surrounding it.

While the challenge would be fun, its outside of my focus and time right now, so I can't help you much there.
