### ISSUE TITLE
The viewer refuses to synchronize with the server.

### ISSUE THREAD

**Issue by raymoo69** [Zharay/KanColleViewer#31]
This seems to be a relatively new bug that seems to appear from version .370 onwards. Occasionally the viewer stops updating information about the fleets, like composition, HP, or, if it's a secondary fleet, the expedition countdown. Once this happens the only solution is to restart the viewer, but it helps only for a short while.

**Comment by Zharay** [comment]
It was around that point that I started using a new way of doing ship types. Don't think there was anything in there that changed the way things are updated. Do you happen to have any kind of error log where the exe is at? If you do, attach it here.

**Comment by raymoo69** [comment]
I didn't encounter the problem since the last update, but there's a similar issue. When doing something that doesn't involve the main screen, the viewer doesn't synchronize with the game up until you go back there. Didn't find any error logs.

**Comment by raymoo69** [comment]
Nope, it's back. No error log here, either.

**Comment by Zharay** [comment]
How are you running KCV? Are you using Win8 and the generated App link in metro? KCV only updates when you actually perform something or when you reach the main page, so things like timers  get to 00:00:00 and then stop. Other problems come into play if you're computer's time is off and it shows up in the game as well.

**Comment by raymoo69** [comment]
I'm using it on Win7 x64. I rechecked the time and even changed the timezone, but it doesn't help. What I noticed is that only fleet status and expedition countdown are affected, everything else (including repair) updates without problems.
