### ISSUE TITLE
LOS calculator

### ISSUE THREAD

**Issue by raymoo69** [Zharay/KanColleViewer#35]
Seems like it's going to be crucial this event, so I think it'd be a good idea if you include it similarly to Air Superiority value.

**Comment by Zharay** [comment]
It'll be quick to add this if it indeed requires high LOS to get to boss node in the next event (which it does... for some reason I'm thinking it would also require high LOS just to hit the boss itself in battle...)

**Comment by Zharay** [comment]
Implemented as of past 2 releases~
