### ISSUE TITLE
Issue Connecting (Internal Proxy Server Issue?)

### ISSUE THREAD

**Issue by Daikyi** [Zharay/KanColleViewer#36]
Been having a little trouble with getting this to work properly:

So the page displayed that should be the dmm page comes out to look like this:
![](http://i.imgur.com/9RzLI0y.png)

And after the refresh, something about a proxy server?
![](http://i.imgur.com/ALPpEOQ.png)

I have the NET framework installed (i'm assuming the program wouldn't even run otherwise)
flash player's completely updated (shouldn't matter either)
under IE, internet options, the connections tab is all blank, and i'm able to load kancolle through IE (api link or dmm site) just fine.
I've tried changing the internal proxy (after confirming through netstat -bano in cmd) that there's no other process hogging that port, but to no avail.  I've also tried resetting IE and re-dling the program, but nothing seems to be working.

Any ideas what's going wrong?

**Comment by Zharay** [comment]
Have you tried updating IE?

**Comment by Daikyi** [comment]
yes, i have the most recent version installed apparantly

**Comment by Daikyi** [comment]
I'm not sure, but would the absence of a certain service screw with the internal proxy?

**Comment by Zharay** [comment]
Its not a service that you need other than .NET 4.5, Windows 7/8, and an updated version of IE. It could also be anti-virus software blocking the proxy through their own firewall.

**Comment by Zharay** [comment]
From the looks of it, after searching a bit, it seems that the likely cause is either one of the following
- KCV closed pre-maturely for you and it did not get to clear its own internal proxy settings (ie. the last instance of KCV is still running)
- Another program has already taken the port that KCV uses (37564) thus it won't connect.

A reboot to the PC should fix the first part, but the second may just have to be some random program using the same port.

If you want, try changing the port in the KanColleViewer.exe.config file. Search for 37564 and change the number to 37565 or some other random number (just don't make it too big). This should solve the problem.

**Comment by Daikyi** [comment]
Unfortunately, neither of those actually worked.  I've checked anti-virus software + firewalls, fiddled w/ the port, and tried doing a restart.  Nothing seems to be working, and unless this issue has been affecting other users, it's not that big of a deal, I'll just have to go without using KCV i guess

**Comment by Zharay** [comment]
Then I'm not sure what to do. Something on your system is preventing IE from using the proxy that KCV uses.

**Comment by Daikyi** [comment]
Just upgraded computer, issue fixed itself
