### ISSUE TITLE
"Waiting for KanColle to start" after starting KanColle

### ISSUE THREAD

**Issue by AyaKyunik** [Zharay/KanColleViewer#37]
Seems like after the 23rd April update, KCV can't detect that the game has started?
Sitting on the main screen with KCV still waiting for KanColle to start.
Tried horizontal and vertical.
Using KanColleViewer.v2.5.r420.

**Comment by AyaKyunik** [comment]
Ah, also, using Win 8.1 64bit

**Comment by Xar1s** [comment]
Everyone actually has this problem,i just hope the devs will find a solution,because KCV is a really great tool,and it becomes even better after every update.

**Comment by bgoztgeto** [comment]
i have the same problem too...
win 7 32 bit, IE 11, flashplayer ver 13

**Comment by Zharay** [comment]
Fixed~
