### ISSUE TITLE
No translation part on vertical and horizontal kancolleviewer

### ISSUE THREAD

**Issue by yamada25** [Zharay/KanColleViewer#38]
Just now I updated my viewer with the latest one, there is no translation part on it, not sure if it's a bug.
http://i.imgur.com/LmzOFbd.jpg (vertical)
http://i.imgur.com/dFVbAee.jpg (horiontal)

**Comment by DonaNobisPacem** [comment]
I think it's more about the new patch breaking the viewer than a bug.

**Comment by Tetsamaru** [comment]
Ya, the latest Spring event patch just bugged upt he entire viewer, probably gonna need to wait on a new update.

**Comment by Zharay** [comment]
Fixed~
