### ISSUE TITLE
Missing fleet info and expedition timer

### ISSUE THREAD

**Issue by Xenn1** [Zharay/KanColleViewer#39]
![capture](https://cloud.githubusercontent.com/assets/7388120/2782364/b1278db6-cb1e-11e3-8d22-f2866f984763.JPG)

grabacr's version works for me. using the latest 2.6 beta version.

**Comment by Zharay** [comment]
Any error log where the exe file is at?

**Comment by Xenn1** [comment]
Nope. Everything else works including Ship/Eq list.

**Comment by Zharay** [comment]
Tried clearing cache and re-opening it again? Don't see why it should be any different from grabacr's version.

**Comment by Xenn1** [comment]
Clearing cache worked.

**Comment by Zharay** [comment]
Sweet, I'll be sure to add this info somewhere.
