### ISSUE TITLE
Fleets and Expeditions not show, and Bucket not update

### ISSUE THREAD

**Issue by aranmaso** [Zharay/KanColleViewer#41]
I'm try to clear my cache and cookie from IE now, but none of them work even after download the program again
![ss 2557-04-25 at 12 21 50](https://cloud.githubusercontent.com/assets/5458052/2792643/83ea6406-cbd5-11e3-8d48-53805562f09d.png)

**Comment by Zharay** [comment]
Its a known issue. A fix that seems to work every now and then is to cycle back and forth between your main menu and another screen to force it to update again.
