### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by DonaNobisPacem** [Zharay/KanColleViewer#43]
I've been encountering a problem with the latest release of KCV. Sometimes, more often than not, the viewer ignores the translations and reverts back to Japanese. At first I thought it was because my system was set to Japanese locale, so I selected the 'English' option in the Language tab. Still the problem persisted. The change also seems to be random, as there are times when I restart the viewer that it just fixes itself.

![screenshot_2](https://cloud.githubusercontent.com/assets/2908239/2796955/9310aef2-cc1d-11e3-8894-9130033123f2.png)

**Comment by Zharay** [comment]
I ran into this bug myself before the update as well. If you turn off translations and then turn it back on again, the UI won't forcefully reload the translations. You have to close it and open it back up again for it to go back to being translated. 

Its an annoying bug that isn't attached to the new update that I'll have to fix.
