### ISSUE TITLE
Fleet tracking error when swapping ships

### ISSUE THREAD

**Issue by cassist** [Zharay/KanColleViewer#44]
Not entirely sure how to reproduce it, but it's happened twice.
Swapped a ship out for another, and the fleet tracker thinks the ship that has been swapped out is the only ship in the fleet.

Fixed by returning to main screen.

![u6yzgfu](https://cloud.githubusercontent.com/assets/5640908/2797435/81a56aee-cc2d-11e3-8bf0-61e38b8605ea.jpg)

**Comment by Zharay** [comment]
A known bug. Happens most notably when you modernize a ship or remodel them as well. A fix is to go back to the main menu in game, but then other bugs start appearing afterwards.

Following that the timers will seem to be laggy as well.
